name: 'Now Deploy'
description: 'Deploys a project to Now'
inputs:
  configs:
    description: 'Stringified configs'
    default: '{}'
  build-path:
    description: 'Path of the build directory'
outputs:
  url:
    description: 'The url of the deployment'
runs:
  using: 'node12'
  main: 'dist/index.js'
